[package]
name = "MoveForgeExamples"
version = "1.0.0"
authors = ["MoveForge Team"]

[addresses]
paraforge_examples = "_"
moveforge_nft = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "mainnet"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "mainnet"
